### ISSUE TITLE
ERROR: MethodError: no method matching start(::Void)

### ISSUE THREAD

**Issue by josefsachsconning** [Keno/Gallium.jl#122]
Using master branches of Julia and Gallium and its dependencies.
```
AWS-Sachs-Ubuntu$ usr/bin/julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+4807 (2016-06-16 09:55 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit e124787 (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> using Gallium
WARNING: pointer_to_array{T}(p::Ptr{T},d::Union{Integer,Tuple{Vararg{Integer}}},own::Bool=false) is deprecated, use unsafe_wrap(Array,p,d,own) instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in pointer_to_array(::Ptr{UInt8}, ::Tuple{UInt8}, ::Bool) at ./deprecated.jl:50
 in __init__() at /home/sachs/.julia/v0.5/Gallium/src/Hooking/Hooking.jl:265
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:174
 in _require_from_serialized(::Int64, ::Symbol, ::Bool) at ./loading.jl:202
 in require(::Symbol) at ./loading.jl:332
 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
while loading no file, in expression starting on line 0
WARNING: pointer_to_array{T}(p::Ptr{T},d::Union{Integer,Tuple{Vararg{Integer}}},own::Bool=false) is deprecated, use unsafe_wrap(Array,p,d,own) instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in pointer_to_array(::Ptr{UInt8}, ::Tuple{UInt64}, ::Bool) at ./deprecated.jl:50
 in __init__() at /home/sachs/.julia/v0.5/Gallium/src/Hooking/Hooking.jl:280
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:174
 in _require_from_serialized(::Int64, ::Symbol, ::Bool) at ./loading.jl:202
 in require(::Symbol) at ./loading.jl:332
 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
while loading no file, in expression starting on line 0

julia> function myfunction1(x)
           return "monadic"
       end
myfunction1 (generic function with 1 method)

julia> bp = Gallium.breakpoint(myfunction1)
ERROR: MethodError: no method matching start(::Void)
 in _breakpoint_method(::Method, ::Gallium.Breakpoint, ::Gallium.##66#67) at /home/sachs/.julia/v0.5/Gallium/src/Gallium.jl:654
 in add_meth_to_bp!(::Gallium.Breakpoint, ::Method, ::Function) at /home/sachs/.julia/v0.5/Gallium/src/Gallium.jl:701
 in breakpoint(::Function) at /home/sachs/.julia/v0.5/Gallium/src/Gallium.jl:773
 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

**Comment by Keno** [comment]
This particular issue is fixed, but there's still some discussion in https://github.com/JuliaLang/julia/pull/15918 as to whether the fixed I used is correct. Also, you'll probably want to wait for https://github.com/JuliaLang/julia/pull/16976 being merged, since you get a whole bunch of errors otherwise.

**Comment by josefsachsconning** [comment]
I still get an error.  Same issue, or should I create a separate issue?
```
AWS-Sachs-Ubuntu$ usr/bin/julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+4832 (2016-06-17 06:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 858371f (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> using Gallium

julia> function myfunction1(x)
                  return "monadic"
              end
myfunction1 (generic function with 1 method)

julia> bp = Gallium.breakpoint(myfunction1)
ERROR: MethodError: no method matching visit(::Gallium.##66#68{Gallium.Breakpoint,Gallium.##71#72}, ::Void)
Closest candidates are:
  visit(::Any, ::MethodTable)
  visit(::Any, ::TypeMapLevel)
  visit(::Any, ::TypeMapEntry)
 in _breakpoint_method(::Method, ::Gallium.Breakpoint, ::Gallium.##71#72) at /home/sachs/.julia/v0.5/Gallium/src/Gallium.jl:701
 in add_meth_to_bp!(::Gallium.Breakpoint, ::Method, ::Function) at /home/sachs/.julia/v0.5/Gallium/src/Gallium.jl:749
 in breakpoint(::Function) at /home/sachs/.julia/v0.5/Gallium/src/Gallium.jl:821
 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

**Comment by malmaud** [comment]
Same, on OS X

**Comment by Keno** [comment]
I'm looking into it.

**Comment by josefsachsconning** [comment]
Works now.
